# deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: my-container
          image: cgidemoacr.azurecr.io/cgi-demo:latest
          ports:
            - containerPort: 8080

